'use strict'

module.exports = function generateSwift(hrpc) {
  let hasSend = false
  let hasNormal = false
  let hasResponseStream = false
  let hasRequestStream = false
  let hasDuplex = false
  let hasStructTypes = false
  for (const h of hrpc.handlers) {
    const reqStream = h.request.stream === true
    const respStream = h.response?.stream === true
    if (h.request.send === true && h.response == null) hasSend = true
    else if (reqStream && respStream) hasDuplex = true
    else if (reqStream) hasRequestStream = true
    else if (respStream) hasResponseStream = true
    else hasNormal = true
    if (h.request.name.includes('/')) hasStructTypes = true
    if (h.response?.name.includes('/')) hasStructTypes = true
  }

  const imports = ['import BareRPC', 'import CompactEncoding', 'import Foundation']
  if (hasStructTypes) imports.push('import Schema')

  const lines = [
    '// This file is autogenerated by the hrpc compiler',
    '',
    ...imports,
    '',
    'public class HRPC {',
    '  private let _rpc: RPC',
    '  private let _forwarder: _HRPCDelegateForwarder',
    '  private var _handlers: [String: Any] = [:]'
  ]

  if (hasResponseStream) {
    const ids = hrpc.handlers
      .filter((h) => !h.request.stream && h.response?.stream === true)
      .map((h) => h.id)
    lines.push(`  private let _responseStreamCommands: Set<UInt> = [${ids.join(', ')}]`)
  }

  if (hasRequestStream) {
    const ids = hrpc.handlers
      .filter((h) => h.request.stream === true && !h.response?.stream)
      .map((h) => h.id)
    lines.push(`  private let _requestStreamCommands: Set<UInt> = [${ids.join(', ')}]`)
  }

  if (hasDuplex) {
    const ids = hrpc.handlers
      .filter((h) => h.request.stream === true && h.response?.stream === true)
      .map((h) => h.id)
    lines.push(`  private let _duplexCommands: Set<UInt> = [${ids.join(', ')}]`)
  }

  lines.push(
    '',
    '  public init<D: RPCDelegate>(delegate: D) {',
    '    let forwarder = _HRPCDelegateForwarder(transport: delegate)',
    '    self._rpc = RPC(delegate: forwarder)',
    '    self._forwarder = forwarder',
    '    forwarder.hrpc = self',
    '  }',
    '',
    '  public func receive(_ data: Data) async {',
    '    await self._rpc.receive(data)',
    '  }',
    ''
  )

  // Generate client + server methods for each handler
  for (const handler of hrpc.handlers) {
    const isSend = handler.request.send === true && handler.response == null
    lines.push(...generateMethods(handler, isSend))
  }

  // Generate dispatch methods
  const hasAnyRequest = hasNormal || hasResponseStream || hasRequestStream || hasDuplex
  if (hasAnyRequest) {
    lines.push(...generateDispatchRouter({ hasNormal, hasResponseStream, hasRequestStream, hasDuplex }))
    if (hasNormal) lines.push(...generateNormalDispatch(hrpc.handlers))
    if (hasResponseStream) lines.push(...generateResponseStreamDispatch(hrpc.handlers))
    if (hasRequestStream) lines.push(...generateRequestStreamDispatch(hrpc.handlers))
    if (hasDuplex) lines.push(...generateDuplexDispatch(hrpc.handlers))
  }
  if (hasSend) {
    lines.push(...generateEventDispatch(hrpc.handlers))
  }

  // Private encode/decode helpers
  lines.push(
    '',
    '  private func _encode<C: Codec>(_ codec: C, _ value: C.Value) throws -> Data {',
    '    var state = State()',
    '    codec.preencode(&state, value)',
    '    state.allocate()',
    '    try codec.encode(&state, value)',
    '    return state.buffer',
    '  }',
    '',
    '  private func _decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {',
    '    var state = State(data)',
    '    return try codec.decode(&state)',
    '  }',
    '}'
  )

  // Forwarder class — bridges RPCDelegate protocol to HRPC's internal dispatch
  const forwarderLines = [
    '',
    'private final class _HRPCDelegateForwarder: RPCDelegate {',
    '  let transport: any RPCDelegate',
    '  weak var hrpc: HRPC?',
    '',
    '  init<D: RPCDelegate>(transport: D) {',
    '    self.transport = transport',
    '  }',
    '',
    '  func rpc(_ rpc: RPC, send data: Data) {',
    '    transport.rpc(rpc, send: data)',
    '  }',
    '',
    '  func rpc(_ rpc: RPC, didFailWith error: Error) {',
    '    transport.rpc(rpc, didFailWith: error)',
    '  }'
  ]

  if (hasAnyRequest) {
    forwarderLines.push(
      '',
      '  func rpc(_ rpc: RPC, didReceiveRequest req: IncomingRequest) async throws {',
      '    await hrpc?._dispatchRequest(req)',
      '  }'
    )
  }


  if (hasSend) {
    forwarderLines.push(
      '',
      '  func rpc(_ rpc: RPC, didReceiveEvent event: IncomingEvent) async {',
      '    await hrpc?._dispatchEvent(event)',
      '  }'
    )
  }

  forwarderLines.push('}')
  lines.push(...forwarderLines)

  return lines.join('\n') + '\n'
}

// --- Helpers ---

function generateMethods(handler, isSend) {
  const methodName = toSwiftMethodName(handler.name)
  const onName = 'on' + methodName[0].toUpperCase() + methodName.slice(1)
  const reqType = swiftType(handler.request.name)
  const reqCodec = swiftCodec(handler.request.name)
  const fqn = handler.name
  const id = handler.id
  const lines = []

  if (isSend) {
    // Client: fire-and-forget, async so callers can await the actual send
    lines.push(
      `  // Send-only — client (fire and forget)`,
      `  public func ${methodName}(_ args: ${reqType}? = nil) async throws {`,
      `    let encoded = try args.map { try _encode(${reqCodec}, $0) }`,
      `    await _rpc.event(${id}, data: encoded)`,
      `  }`,
      ''
    )
    // Server registration
    lines.push(
      `  public func ${onName}(_ handler: @escaping (${reqType}?) async -> Void) {`,
      `    _handlers["${fqn}"] = handler`,
      `  }`,
      ''
    )
  } else if (handler.request.stream === true && handler.response?.stream === true) {
    // Duplex — both sides stream
    lines.push(
      `  // Duplex — client`,
      `  public func ${methodName}(_ body: (OutgoingStream, IncomingStream) async throws -> Void) async throws {`,
      `    let (outgoing, incoming) = try await _rpc.createBidirectionalStream(command: ${id})`,
      `    do { try await body(outgoing, incoming) } catch {`,
      `      await outgoing.destroy(error: RPCRemoteError(message: error.localizedDescription, code: "STREAM_ERROR"))`,
      `      throw error`,
      `    }`,
      `  }`,
      ''
    )
    lines.push(
      `  public func ${onName}(_ handler: @escaping (IncomingStream, OutgoingStream) async throws -> Void) {`,
      `    _handlers["${fqn}"] = handler`,
      `  }`,
      ''
    )
  } else if (handler.request.stream === true) {
    const respType = swiftType(handler.response.name)
    const respCodec = swiftCodec(handler.response.name)
    // Client: takes a body closure for writing; end() is called automatically before awaiting reply
    lines.push(
      `  // Request-stream — client`,
      `  public func ${methodName}(_ body: (OutgoingStream) async throws -> Void) async throws -> ${respType}? {`,
      `    let (outgoing, awaitReply) = try await _rpc.streamRequest(command: ${id})`,
      `    do { try await body(outgoing) } catch {`,
      `      await outgoing.destroy(error: RPCRemoteError(message: error.localizedDescription, code: "STREAM_ERROR"))`,
      `      throw error`,
      `    }`,
      `    await outgoing.end()`,
      `    guard let raw = try await awaitReply() else { return nil }`,
      `    return try _decode(${respCodec}, raw)`,
      `  }`,
      ''
    )
    lines.push(
      `  public func ${onName}(_ handler: @escaping (IncomingStream) async throws -> ${respType}?) {`,
      `    _handlers["${fqn}"] = handler`,
      `  }`,
      ''
    )
  } else if (handler.response?.stream === true) {
    // Client: sends optional data, gets back a stream of response chunks
    lines.push(
      `  // Response-stream — client`,
      `  public func ${methodName}(_ args: ${reqType}? = nil) async throws -> IncomingStream {`,
      `    let encoded = try args.map { try _encode(${reqCodec}, $0) }`,
      `    return try await _rpc.requestWithResponseStream(command: ${id}, data: encoded)`,
      `  }`,
      ''
    )
    // Server registration
    lines.push(
      `  public func ${onName}(_ handler: @escaping (${reqType}?, OutgoingStream) async throws -> Void) {`,
      `    _handlers["${fqn}"] = handler`,
      `  }`,
      ''
    )
  } else {
    const respType = swiftType(handler.response.name)
    const respCodec = swiftCodec(handler.response.name)
    // Client: async throws, returns response
    lines.push(
      `  // Request/response — client`,
      `  public func ${methodName}(_ args: ${reqType}? = nil) async throws -> ${respType} {`,
      `    let encoded = try args.map { try _encode(${reqCodec}, $0) }`,
      `    guard let raw = try await _rpc.request(${id}, data: encoded) else {`,
      `      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")`,
      `    }`,
      `    return try _decode(${respCodec}, raw)`,
      `  }`,
      ''
    )
    // Server registration
    lines.push(
      `  public func ${onName}(_ handler: @escaping (${reqType}?) async throws -> ${respType}) {`,
      `    _handlers["${fqn}"] = handler`,
      `  }`,
      ''
    )
  }

  return lines
}

function generateNormalDispatch(handlers) {
  const normalHandlers = handlers.filter(
    (h) =>
      !(h.request.send === true && h.response == null) && !h.request.stream && !h.response?.stream
  )
  const lines = [
    '  private func _dispatchNormal(_ req: IncomingRequest) async {',
    '    switch req.command {'
  ]

  for (const handler of normalHandlers) {
    const fqn = handler.name
    const id = handler.id
    const reqType = swiftType(handler.request.name)
    const reqCodec = swiftCodec(handler.request.name)
    const respType = swiftType(handler.response.name)
    const respCodec = swiftCodec(handler.response.name)
    const handlerType = `(${reqType}?) async throws -> ${respType}`

    lines.push(
      `    case ${id}:   // ${handler.name}`,
      `      guard let handler = _handlers["${fqn}"] as? ${handlerType} else { await req.reject("No handler registered", code: "NO_HANDLER"); return }`,
      `      do {`,
      `        let args: ${reqType}? = try req.data.map { try _decode(${reqCodec}, $0) }`,
      `        let response = try await handler(args)`,
      `        await req.reply(try _encode(${respCodec}, response))`,
      `      } catch {`,
      `        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")`,
      `      }`
    )
  }

  lines.push(
    '    default:',
    '      await req.reject("Unknown command", code: "UNKNOWN_COMMAND")',
    '    }',
    '  }'
  )

  return lines
}

function generateDispatchRouter({ hasNormal, hasResponseStream, hasRequestStream, hasDuplex }) {
  const lines = ['  fileprivate func _dispatchRequest(_ req: IncomingRequest) async {']

  if (hasDuplex) {
    lines.push(
      '    if req.requestStream != nil && _duplexCommands.contains(req.command) {',
      '      await _dispatchDuplex(req)',
      '      return',
      '    }'
    )
  }

  if (hasRequestStream) {
    lines.push(
      '    if req.requestStream != nil && _requestStreamCommands.contains(req.command) {',
      '      await _dispatchRequestStream(req)',
      '      return',
      '    }'
    )
  }

  if (hasResponseStream) {
    lines.push(
      '    if _responseStreamCommands.contains(req.command) {',
      '      await _dispatchResponseStream(req)',
      '      return',
      '    }'
    )
  }

  if (hasNormal) {
    lines.push('    await _dispatchNormal(req)')
  } else {
    lines.push('    await req.reject("Unknown command", code: "UNKNOWN_COMMAND")')
  }

  lines.push('  }')
  return lines
}

function generateResponseStreamDispatch(handlers) {
  const streamHandlers = handlers.filter((h) => !h.request.stream && h.response?.stream === true)
  const lines = [
    '  private func _dispatchResponseStream(_ req: IncomingRequest) async {',
    '    switch req.command {'
  ]

  for (const handler of streamHandlers) {
    const fqn = handler.name
    const id = handler.id
    const reqType = swiftType(handler.request.name)
    const reqCodec = swiftCodec(handler.request.name)
    const handlerType = `(${reqType}?, OutgoingStream) async throws -> Void`

    lines.push(
      `    case ${id}:   // ${handler.name}`,
      `      guard let handler = _handlers["${fqn}"] as? ${handlerType} else { await req.reject("No handler registered", code: "NO_HANDLER"); return }`,
      `      let args: ${reqType}? = try? req.data.map { try _decode(${reqCodec}, $0) }`,
      `      guard let outStream = await req.createResponseStream() else { return }`,
      `      do {`,
      `        try await handler(args, outStream)`,
      `      } catch {`,
      `        await outStream.destroy(error: RPCRemoteError(message: error.localizedDescription, code: "HANDLER_ERROR"))`,
      `      }`
    )
  }

  lines.push(
    '    default:',
    '      await req.reject("Unknown command", code: "UNKNOWN_COMMAND")',
    '    }',
    '  }'
  )
  return lines
}

function generateRequestStreamDispatch(handlers) {
  const streamHandlers = handlers.filter((h) => h.request.stream === true && !h.response?.stream)
  const lines = [
    '  private func _dispatchRequestStream(_ req: IncomingRequest) async {',
    '    switch req.command {'
  ]

  for (const handler of streamHandlers) {
    const fqn = handler.name
    const id = handler.id
    const respType = swiftType(handler.response.name)
    const respCodec = swiftCodec(handler.response.name)
    const handlerType = `(IncomingStream) async throws -> ${respType}?`

    lines.push(
      `    case ${id}:   // ${handler.name}`,
      `      guard let handler = _handlers["${fqn}"] as? ${handlerType} else { await req.reject("No handler registered", code: "NO_HANDLER"); return }`,
      `      guard let requestStream = req.requestStream else { await req.reject("Expected request stream", code: "PROTOCOL_ERROR"); return }`,
      `      do {`,
      `        let response = try await handler(requestStream)`,
      `        if let response {`,
      `          await req.reply(try _encode(${respCodec}, response))`,
      `        } else {`,
      `          await req.reply(nil)`,
      `        }`,
      `      } catch {`,
      `        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")`,
      `      }`
    )
  }

  lines.push(
    '    default:',
    '      await req.reject("Unknown command", code: "UNKNOWN_COMMAND")',
    '    }',
    '  }'
  )
  return lines
}

function generateDuplexDispatch(handlers) {
  const duplexHandlers = handlers.filter((h) => h.request.stream === true && h.response?.stream === true)
  const lines = [
    '  private func _dispatchDuplex(_ req: IncomingRequest) async {',
    '    switch req.command {'
  ]

  for (const handler of duplexHandlers) {
    const fqn = handler.name
    const id = handler.id
    const handlerType = `(IncomingStream, OutgoingStream) async throws -> Void`

    lines.push(
      `    case ${id}:   // ${handler.name}`,
      `      guard let handler = _handlers["${fqn}"] as? ${handlerType} else { await req.reject("No handler registered", code: "NO_HANDLER"); return }`,
      `      guard let requestStream = req.requestStream else { await req.reject("Expected request stream", code: "PROTOCOL_ERROR"); return }`,
      `      guard let outStream = await req.createResponseStream() else { return }`,
      `      do {`,
      `        try await handler(requestStream, outStream)`,
      `      } catch {`,
      `        await outStream.destroy(error: RPCRemoteError(message: error.localizedDescription, code: "HANDLER_ERROR"))`,
      `      }`
    )
  }

  lines.push('    default:', '      await req.reject("Unknown command", code: "UNKNOWN_COMMAND")', '    }', '  }')
  return lines
}

function generateEventDispatch(handlers) {
  const sendHandlers = handlers.filter((h) => h.request.send === true && h.response == null)
  const lines = [
    '  fileprivate func _dispatchEvent(_ event: IncomingEvent) async {',
    '    switch event.command {'
  ]

  for (const handler of sendHandlers) {
    const fqn = handler.name
    const id = handler.id
    const reqType = swiftType(handler.request.name)
    const reqCodec = swiftCodec(handler.request.name)
    const handlerType = `(${reqType}?) async -> Void`

    lines.push(
      `    case ${id}:   // ${handler.name}`,
      `      guard let handler = _handlers["${fqn}"] as? ${handlerType} else { return }`,
      `      do {`,
      `        let args: ${reqType}? = try event.data.map { try _decode(${reqCodec}, $0) }`,
      `        await handler(args)`,
      `      } catch { }`
    )
  }

  lines.push('    default:', '      break', '    }', '  }')

  return lines
}

// Maps hyperschema primitive names to { codec, type } for Swift
const SWIFT_PRIMITIVES = {
  uint: { codec: 'Primitive.UInt()', type: 'UInt' },
  uint8: { codec: 'Primitive.UInt8()', type: 'UInt8' },
  uint16: { codec: 'Primitive.UInt16()', type: 'UInt16' },
  uint32: { codec: 'Primitive.UInt32()', type: 'UInt32' },
  uint64: { codec: 'Primitive.UInt64()', type: 'UInt64' },
  int: { codec: 'Primitive.Int()', type: 'Int' },
  int8: { codec: 'Primitive.Int8()', type: 'Int8' },
  int16: { codec: 'Primitive.Int16()', type: 'Int16' },
  int32: { codec: 'Primitive.Int32()', type: 'Int32' },
  int64: { codec: 'Primitive.Int64()', type: 'Int64' },
  float32: { codec: 'Primitive.Float32()', type: 'Float' },
  float64: { codec: 'Primitive.Float64()', type: 'Double' },
  bool: { codec: 'Primitive.Bool()', type: 'Bool' },
  string: { codec: 'Primitive.UTF8()', type: 'String' },
  utf8: { codec: 'Primitive.UTF8()', type: 'String' },
  buffer: { codec: 'Primitive.Buffer()', type: 'Data' }
}

// Returns the Swift type name for a schema type name (primitive or struct)
function swiftType(name) {
  if (SWIFT_PRIMITIVES[name]) return SWIFT_PRIMITIVES[name].type
  if (name.includes('/')) return toSwiftTypeName(name)
  throw new Error(`HRPC Swift codegen: unsupported primitive type '${name}'`)
}

// Returns the Swift codec expression for a schema type name
function swiftCodec(name) {
  if (SWIFT_PRIMITIVES[name]) return SWIFT_PRIMITIVES[name].codec
  if (name.includes('/')) return toSwiftInstanceName(name)
  throw new Error(`HRPC Swift codegen: unsupported primitive type '${name}'`)
}

// '@namespace/some-command' → 'someCommand'
function toSwiftMethodName(name) {
  const pascal = toSwiftTypeName(name)
  return pascal[0].toLowerCase() + pascal.slice(1)
}

// '@namespace/some-type-name' → 'SomeTypeName'
function toSwiftTypeName(name) {
  const bare = name.includes('/') ? name.slice(name.indexOf('/') + 1) : name
  return bare
    .split('-')
    .map((s) => (s.length ? s[0].toUpperCase() + s.slice(1) : s))
    .join('')
}

// '@namespace/some-type-name' → 'someTypeName'
function toSwiftInstanceName(name) {
  const pascal = toSwiftTypeName(name)
  return pascal[0].toLowerCase() + pascal.slice(1)
}
