'use strict'

module.exports = function generateSwift(hrpc) {
  let hasSend = false
  let hasRequestResponse = false
  for (const h of hrpc.handlers) {
    if (h.request.stream === true || h.response?.stream === true) {
      throw new Error(
        `HRPC Swift codegen: streaming commands are not supported in v1. ` +
          `Handler '${h.name}' uses streaming.`
      )
    }
    if (h.request.send === true && h.response == null) hasSend = true
    else hasRequestResponse = true
  }

  const lines = [
    '// This file is autogenerated by the hrpc compiler',
    '',
    'import BareRPC',
    'import CompactEncoding',
    'import Foundation',
    'import Schema',
    '',
    'public class HRPC {',
    '  private let _rpc: RPC',
    '  private var _handlers: [String: Any] = [:]',
    '',
    '  public init(delegate: RPCDelegate) {',
    '    self._rpc = RPC(delegate: delegate)'
  ]

  if (hasRequestResponse) {
    lines.push(
      '    self._rpc.onRequest = { [weak self] req in',
      '      await self?._dispatchRequest(req)',
      '    }'
    )
  }

  if (hasSend) {
    lines.push(
      '    self._rpc.onEvent = { [weak self] event in',
      '      await self?._dispatchEvent(event)',
      '    }'
    )
  }

  lines.push(
    '  }',
    '',
    '  public func receive(_ data: Data) {',
    '    _rpc.receive(data)',
    '  }',
    ''
  )

  // Generate client + server methods for each handler
  for (const handler of hrpc.handlers) {
    const isSend = handler.request.send === true && handler.response == null
    lines.push(...generateMethods(handler, isSend))
  }

  // Generate dispatch methods
  if (hasRequestResponse) {
    lines.push(...generateRequestDispatch(hrpc.handlers))
  }
  if (hasSend) {
    lines.push(...generateEventDispatch(hrpc.handlers))
  }

  // Private encode/decode helpers
  lines.push(
    '',
    '  private func _encode<C: Codec>(_ codec: C, _ value: C.Value) throws -> Data {',
    '    var state = State()',
    '    codec.preencode(&state, value)',
    '    state.allocate()',
    '    try codec.encode(&state, value)',
    '    return state.buffer',
    '  }',
    '',
    '  private func _decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {',
    '    var state = State(data)',
    '    return try codec.decode(&state)',
    '  }',
    '}'
  )

  return lines.join('\n') + '\n'
}

// --- Helpers ---

function generateMethods(handler, isSend) {
  const methodName = toSwiftMethodName(handler.name)
  const onName = 'on' + methodName[0].toUpperCase() + methodName.slice(1)
  const reqType = toSwiftTypeName(handler.request.name)
  const reqCodec = toSwiftInstanceName(handler.request.name)
  const fqn = handler.name
  const id = handler.id
  const lines = []

  if (isSend) {
    // Client: fire-and-forget, no async, no return
    lines.push(
      `  // Send-only — client (fire and forget)`,
      `  public func ${methodName}(_ args: ${reqType}) throws {`,
      `    let encoded = try _encode(${reqCodec}, args)`,
      `    _rpc.event(${id}, data: encoded)`,
      `  }`,
      ''
    )
    // Server registration
    lines.push(
      `  public func ${onName}(_ handler: @escaping (${reqType}) async -> Void) {`,
      `    _handlers["${fqn}"] = handler`,
      `  }`,
      ''
    )
  } else {
    const respType = toSwiftTypeName(handler.response.name)
    const respCodec = toSwiftInstanceName(handler.response.name)
    // Client: async throws, returns response
    lines.push(
      `  // Request/response — client`,
      `  public func ${methodName}(_ args: ${reqType}) async throws -> ${respType} {`,
      `    let encoded = try _encode(${reqCodec}, args)`,
      `    guard let raw = try await _rpc.request(${id}, data: encoded) else {`,
      `      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")`,
      `    }`,
      `    return try _decode(${respCodec}, raw)`,
      `  }`,
      ''
    )
    // Server registration
    lines.push(
      `  public func ${onName}(_ handler: @escaping (${reqType}) async throws -> ${respType}) {`,
      `    _handlers["${fqn}"] = handler`,
      `  }`,
      ''
    )
  }

  return lines
}

function generateRequestDispatch(handlers) {
  const requestHandlers = handlers.filter((h) => !(h.request.send === true && h.response == null))
  const lines = [
    '  private func _dispatchRequest(_ req: IncomingRequest) async {',
    '    switch req.command {'
  ]

  for (const handler of requestHandlers) {
    const fqn = handler.name
    const id = handler.id
    const reqType = toSwiftTypeName(handler.request.name)
    const reqCodec = toSwiftInstanceName(handler.request.name)
    const respType = toSwiftTypeName(handler.response.name)
    const respCodec = toSwiftInstanceName(handler.response.name)
    const handlerType = `(${reqType}) async throws -> ${respType}`

    lines.push(
      `    case ${id}:   // ${handler.name}`,
      `      guard let handler = _handlers["${fqn}"] as? ${handlerType} else { req.reject("No handler registered", code: "NO_HANDLER"); return }`,
      `      guard let rawData = req.data else {`,
      `        req.reject("Missing request data", code: "BAD_REQUEST")`,
      `        return`,
      `      }`,
      `      do {`,
      `        let args = try _decode(${reqCodec}, rawData)`,
      `        let response = try await handler(args)`,
      `        req.reply(try _encode(${respCodec}, response))`,
      `      } catch {`,
      `        req.reject(error.localizedDescription, code: "HANDLER_ERROR")`,
      `      }`
    )
  }

  lines.push(
    '    default:',
    '      req.reject("Unknown command", code: "UNKNOWN_COMMAND")',
    '    }',
    '  }'
  )

  return lines
}

function generateEventDispatch(handlers) {
  const sendHandlers = handlers.filter((h) => h.request.send === true && h.response == null)
  const lines = [
    '  private func _dispatchEvent(_ event: IncomingEvent) async {',
    '    switch event.command {'
  ]

  for (const handler of sendHandlers) {
    const fqn = handler.name
    const id = handler.id
    const reqType = toSwiftTypeName(handler.request.name)
    const reqCodec = toSwiftInstanceName(handler.request.name)
    const handlerType = `(${reqType}) async -> Void`

    lines.push(
      `    case ${id}:   // ${handler.name}`,
      `      guard let handler = _handlers["${fqn}"] as? ${handlerType} else { return }`,
      `      guard let rawData = event.data else { return }`,
      `      do {`,
      `        let args = try _decode(${reqCodec}, rawData)`,
      `        await handler(args)`,
      `      } catch {`,
      `        _rpc.onError?(error)`,
      `      }`
    )
  }

  lines.push('    default:', '      break', '    }', '  }')

  return lines
}

// '@namespace/some-command' → 'someCommand'
function toSwiftMethodName(name) {
  const pascal = toSwiftTypeName(name)
  return pascal[0].toLowerCase() + pascal.slice(1)
}

// '@namespace/some-type-name' → 'SomeTypeName'
function toSwiftTypeName(name) {
  const bare = name.includes('/') ? name.slice(name.indexOf('/') + 1) : name
  return bare
    .split('-')
    .map((s) => (s.length ? s[0].toUpperCase() + s.slice(1) : s))
    .join('')
}

// '@namespace/some-type-name' → 'someTypeName'
function toSwiftInstanceName(name) {
  const pascal = toSwiftTypeName(name)
  return pascal[0].toLowerCase() + pascal.slice(1)
}
