name: Integrate
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js lts/*
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: 'https://npm.pkg.github.com'
      - uses: swift-actions/setup-swift@v2
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm test
      - run: npm run test:cross-language
